name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-html
    - name: Create test directories and files
      run: |
        mkdir -p tests
        mkdir -p reports/test_reports
        # Create a simple test image for upload tests
        touch tests/test_image.jpg
    - name: Test with pytest
      run: |
        python -m pytest --html=reports/test_reports/report.html --self-contained-html
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: reports/test_reports/report.html
    - name: Check directory structure
      run: |
        find . -type d | sort
        echo "Does templates directory exist?"
        ls -la Website/templates || echo "Directory not found"